apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmg-backend-deployment
  labels:
    app: cmg-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cmg-backend
  template:
    metadata:
      labels:
        app: cmg-backend
    spec:
      containers:
      - name: cmg-backend
        image: 730335406037.dkr.ecr.us-east-2.amazonaws.com/cmg-backend:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
           cpu: 500m
          requests:
           cpu: 200m  
        env:
          - name: DB_USER
            valueFrom: 
              secretKeyRef:
                name: cmg-secret 
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: cmg-secret 
                key: DB_PASSWORD
          - name: DB_HOST
            valueFrom: 
              secretKeyRef:
                name: cmg-secret 
                key: DB_HOST
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: postgres
